package br.com.RestauranteRioBranco.utils.enums;

public enum EBairro {
	JARDIM_BELA_VISTA,
	JARDIM_DOS_ESTADOS,
	JARDIM_EUROPA,
	JARDIM_MORUMBI,
	JARDIM_NOVO_ESTADO,
	JARDIM_ORLANDINI,
	JARDIM_PRIMAVERA,
	ORLEANS_RESIDENCIAL,
	PARK_UNIVERSITARIO,
	SAVANA_PARK,
	SETOR_1,
	SETOR_1A,
	SETOR_2,
	SETOR_3,
	SETOR_4,
	SETOR_5,
	SETOR_6,
	SETOR_7,
	SETOR_8,
	SETOR_INDUSTRIAL
}
